[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-arg=-s", "-C", "link-arg=USE_SDL=2",
    "-C", "link-arg=-s", "-C", "link-arg=MIN_WEBGL_VERSION=2",
    "-C", "link-arg=-s", "-C", "link-arg=MAX_WEBGL_VERSION=2",
    "-C", "link-arg=--embed-file", "-C", "link-arg=resources/fire.png",
    "-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/anotheralien.png",
    "-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/anotheralien.mtl",
    "-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/anotheralien.obj",
    "-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/box.mtl",
    "-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/box.obj",
    "-C", "link-arg=--embed-file", "-C", "link-arg=resources/ground.png",
    "-C", "link-arg=-s", "-C", "link-arg=EXTRA_EXPORTED_RUNTIME_METHODS=[\"ccall\",\"cwrap\"]",
    "-Clink-args=--js-library main.js"
]
